# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - residai

on:
  push:
    branches:
      - main
    paths:
      - 'realestate-ia-site/realestate-ia-site.Server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore "realestate-ia-site/realestate-ia-site.Server/realestate-ia-site.Server.csproj"

      - name: Build with dotnet
        run: dotnet build "realestate-ia-site/realestate-ia-site.Server/realestate-ia-site.Server.csproj" --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish "realestate-ia-site/realestate-ia-site.Server/realestate-ia-site.Server.csproj" -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5BBCA78B82B480FA0F20499F6B21366 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E2CD1CE0FC4C4E77AC820A1D7461D8EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1CA43DDA05464DDCBD20D3C4F169A5DE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'residai'
          slot-name: 'Production'
          package: .
